version: 2

updates:
  - package-ecosystem: gomod
    directory: /vend
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      browser-tests:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /image
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
