#!/usr/bin/env bash
# Create all host-specific appliance state on first boot. Nothing generated by
# this script is present in the published image.
set -euo pipefail

ETC_DIR="${FORGE_ETC_DIR:-/etc/exe-image-forge}"
DATA_DIR="${FORGE_DATA_DIR:-/var/lib/exe-image-forge}"
SOURCE_ROOT="${FORGE_SOURCE_ROOT:-/opt/exe-image-forge/source}"
VEND_BINARY="${FORGE_VEND_BINARY:-/opt/exe-image-forge/vend}"
VM_NAME="${FORGE_HOSTNAME:-$(hostname)}"
IMAGE_PREFIX="${FORGE_IMAGE_PREFIX:-exe-image-forge}"
AUTO_BUILD="${FORGE_AUTO_BUILD:-1}"
CONFIG="$ETC_DIR/config.json"
ENV_FILE="$ETC_DIR/forge.env"
INITIAL_PASSWORD="$DATA_DIR/initial-password"
INITIALIZED="$DATA_DIR/appliance-initialized"

[[ "$VM_NAME" =~ ^[A-Za-z0-9][A-Za-z0-9-]*$ ]] || {
  echo "invalid appliance hostname: $VM_NAME" >&2
  exit 1
}
[[ "$IMAGE_PREFIX" =~ ^[a-z0-9][a-z0-9._/-]*$ ]] || {
  echo "invalid image prefix: $IMAGE_PREFIX" >&2
  exit 1
}
[[ "$AUTO_BUILD" = 0 || "$AUTO_BUILD" = 1 ]] || {
  echo "FORGE_AUTO_BUILD must be 0 or 1" >&2
  exit 1
}

# The marker is written only after the config has a password hash. Preserve the
# password, host name, and every operator change on subsequent boots.
if [[ -f "$INITIALIZED" && -s "$CONFIG" && -s "$ENV_FILE" ]]; then
  exit 0
fi
# Adopt a complete configuration from an earlier installation without
# replacing it. This also makes an appliance upgrade safe if the marker was
# introduced after that VM was initialized.
if [[ -s "$CONFIG" && -s "$ENV_FILE" ]] &&
  python3 - "$CONFIG" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as config_file:
    config = json.load(config_file)
raise SystemExit(0 if config.get("salt") and config.get("hash") else 1)
PY
then
  install -m0600 /dev/null "$INITIALIZED"
  if [[ "$(id -u)" = 0 ]]; then
    chown exedev:exedev "$INITIALIZED"
  fi
  exit 0
fi

install -d -m0755 "$ETC_DIR"
install -d -m0700 "$DATA_DIR" "$DATA_DIR/authhome" "$DATA_DIR/registry"
install -d -m0700 \
  "$DATA_DIR/authhome/.config/gh" \
  "$DATA_DIR/authhome/.config/.wrangler/config" \
  "$DATA_DIR/authhome/.codex" \
  "$DATA_DIR/authhome/.claude" \
  "$DATA_DIR/authhome/.gemini"

umask 0077
tmp_env=$(mktemp "$ETC_DIR/.forge.env.XXXXXX")
tmp_config=$(mktemp "$ETC_DIR/.config.json.XXXXXX")
tmp_password=$(mktemp "$DATA_DIR/.initial-password.XXXXXX")
trap 'rm -f "$tmp_env" "$tmp_config" "$tmp_password"' EXIT

cat >"$tmp_env" <<EOF
FORGE_ROOT="$SOURCE_ROOT"
FORGE_IMAGE_PREFIX="$IMAGE_PREFIX"
FORGE_VM_NAME="$VM_NAME"
FORGE_CONFIG="$CONFIG"
FORGE_STATE="$DATA_DIR/grants.json"
FORGE_AUTH_HOME="$DATA_DIR/authhome"
FORGE_INSTALL_DIR="/opt/exe-image-forge"
FORGE_REGISTRY_DATA="$DATA_DIR/registry"
FORGE_REGISTRY_LOCK="$DATA_DIR/registry.lock"
FORGE_ADDR="127.0.0.1:8000"
FORGE_BASE_IMAGE="$IMAGE_PREFIX/base:latest"
FORGE_COMMAND_PATH="/usr/local/bin/exe-image-forge"
FORGE_SERVICE_NAME="exe-image-forge-vend.service"
FORGE_REGISTRY_NAME="exe-image-forge-registry"
FORGE_TERMINAL_MODE="auth-host"
FORGE_AUTO_BUILD="$AUTO_BUILD"
FORGE_INITIAL_PASSWORD_FILE="$INITIAL_PASSWORD"
FORGE_MIN_FREE_BYTES="2147483648"
FORGE_MAX_DISK_PERCENT="90"
FORGE_BUILD_CACHE_MIN_FREE="5gb"
FORGE_BUILD_CACHE_RESERVED="2gb"
FORGE_ORPHAN_GRACE="2h"
COMPRESSION="zstd"
COMPRESSION_LEVEL="9"
EOF

python3 - "$tmp_config" "$VM_NAME.exe.xyz" "$IMAGE_PREFIX" "$DATA_DIR" <<'PY'
import json
import sys

path, host, prefix, data_dir = sys.argv[1:]
base = f"{prefix}/base"
dev = f"{prefix}/dev"
config = {
    "salt": "",
    "hash": "",
    "pull_host": host,
    "repos": [dev, base],
    "source_image": {dev: f"{dev}:latest", base: f"{base}:latest"},
    "ttl_minutes": 30,
    "vm_token": "",
    "auth_home": f"{data_dir}/authhome",
    "dev_image": f"{dev}:latest",
    "passkey_file": f"{data_dir}/passkeys.json",
}
with open(path, "w", encoding="utf-8") as config_file:
    json.dump(config, config_file, indent=2)
    config_file.write("\n")
PY

python3 - "$tmp_password" <<'PY'
import secrets
import sys

with open(sys.argv[1], "w", encoding="utf-8") as password_file:
    password_file.write(secrets.token_urlsafe(24) + "\n")
PY

mv -f "$tmp_env" "$ENV_FILE"
mv -f "$tmp_config" "$CONFIG"
mv -f "$tmp_password" "$INITIAL_PASSWORD"
trap - EXIT

"$VEND_BINARY" -set-password -config "$CONFIG" <"$INITIAL_PASSWORD" >/dev/null

chmod 0640 "$ENV_FILE"
chmod 0600 "$CONFIG" "$INITIAL_PASSWORD"
install -m0600 /dev/null "$INITIALIZED"
if [[ "$(id -u)" = 0 ]]; then
  chown root:exedev "$ENV_FILE"
  chown -R exedev:exedev "$CONFIG" "$DATA_DIR"
fi

echo "Exe Image Forge appliance initialized for $VM_NAME."
